spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    url:
    password:

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
