export const LOCAL_STORAGE_KEY = {
  SEARCH_KINDS_KEY: "SEARCH_KINDS_KEY",
  SEARCH_TAGS_KEY: "SEARCH_TAGS_KEY",
  SEARCH_INGREDIENTS_KEY: "SEARCH_INGREDIENTS_KEY",
  UPLOAD_NAME_KEY: "UPLOAD_NAME_KEY",
  UPLOAD_DESCRIPTION_KEY: "UPLOAD_DESCRIPTION_KEY",
  UPLOAD_INGREDIENT_KEY: "UPLOAD_INGREDIENT_KEY",
  UPLOAD_PHOTO_FILE_KEY: "UPLOAD_PHOTO_FILE_KEY",
  UPLOAD_STEPS_KEY: "UPLOAD_STEPS_KEY",
  UPLOAD_TAGS_KEY: "UPLOAD_TAGS_KEY",
  UPLOAD_ALCOHOLS_KEY: "UPLOAD_ALCOHOLS_KEY",
};
