spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://knowalcohol2.cr2bymiqbhd9.ap-northeast-2.rds.amazonaws.com:3306/knowalcohol?serverTimezone=UTC&characterEncoding=UTF-8
    password: 123456789

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true